services:
  rasa:
    build: .
    volumes:
      - ./:/app
    command: run --enable-api --cors "*" 
    ports:
      - "5005:5005"
    networks:
      - rasa-network

  action-server:
    build: 
      context: ./actions
    ports:
      - "5055:5055"
    networks:
      - rasa-network

networks:
  rasa-network:
    driver: bridge
